### ISSUE TITLE
implement session key validation route for third party web apps

### ISSUE THREAD

**Issue by slayerpart** [HPI-DeepLearning/CaptchaService#19]
Since the User could trick the JS Code and set the validation flag to true he would submit the form to the third party web app. In order to make sure that a user has correctly solved the captcha the web app has to validate the session key and ask our service "was this session correctly solved recently?" - So that the user can't skip the captcha validation mechanism.

Input would be the session key and a boolean should be returned.

**Comment by StarkRobert** [comment]
- implement expiration delay

**Comment by hendraet** [comment]
done
