### ISSUE TITLE
bug in add_proposal?

### ISSUE THREAD

**Issue by Bartzi** [HPI-DeepLearning/CaptchaService#8]
in `captcha_service/models.py` you have the following code:

    def add_proposal(self, proposal):
            self.proposals['proposal'] += 1
            self.save()

Shouldn't it be `self.proposals[proposal] += 1` ?

**Comment by slayerpart** [comment]
Yes you are right. Currently we don't use this method, because we solely have solved captchas.  I will fix this. Thanks!
